"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Operation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Operation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUCCESS: _Operation.ValueType  # 0
    FAILURE: _Operation.ValueType  # 1
    DELIVER_MESSAGE_NOW: _Operation.ValueType  # 2
    LOGIN: _Operation.ValueType  # 3
    CREATE_ACCOUNT: _Operation.ValueType  # 4
    DELETE_ACCOUNT: _Operation.ValueType  # 5
    LIST_ACCOUNTS: _Operation.ValueType  # 6
    SEND_MESSAGE: _Operation.ValueType  # 7
    READ_MESSAGE: _Operation.ValueType  # 8
    DELETE_MESSAGE: _Operation.ValueType  # 9

class Operation(_Operation, metaclass=_OperationEnumTypeWrapper): ...

SUCCESS: Operation.ValueType  # 0
FAILURE: Operation.ValueType  # 1
DELIVER_MESSAGE_NOW: Operation.ValueType  # 2
LOGIN: Operation.ValueType  # 3
CREATE_ACCOUNT: Operation.ValueType  # 4
DELETE_ACCOUNT: Operation.ValueType  # 5
LIST_ACCOUNTS: Operation.ValueType  # 6
SEND_MESSAGE: Operation.ValueType  # 7
READ_MESSAGE: Operation.ValueType  # 8
DELETE_MESSAGE: Operation.ValueType  # 9
global___Operation = Operation

@typing.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        info: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info"]) -> None: ...

global___Request = Request

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    operation: global___Operation.ValueType
    @property
    def info(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        operation: global___Operation.ValueType = ...,
        info: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "operation", b"operation"]) -> None: ...

global___Response = Response
